FROM node:18.19.0 as builder

WORKDIR /app/storefront

COPY . . 

RUN rm -rf node_modules

RUN apt-get update

RUN yarn global add gatsby-cli

RUN yarn add sharp

RUN yarn install

RUN gatsby build

FROM nginx

EXPOSE 80

COPY --from=builder /app/storefront/public /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
